version: "3.9"

services:
  devopsdb:
    container_name: devopsdb
    image: vasuch2626/db:v1
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: vasuch2626/javapp:v1
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
